-- Users, projects (many-to-many through project_members), the Jenkins jobs of a project (pipelines)
-- and the analyses of those jobs' builds. Only the relevant log lines and the last 200 lines are stored;
-- the full console log stays on Jenkins.

CREATE TABLE users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR(100) NOT NULL UNIQUE,
    display_name VARCHAR(200) NOT NULL,
    role         VARCHAR(20)  NOT NULL CHECK (role IN ('ADMIN', 'USER')),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE projects (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200) NOT NULL,
    description TEXT,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE project_members (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects (id),
    user_id    BIGINT NOT NULL REFERENCES users (id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (project_id, user_id)
);

-- "Which Jenkins job does this project use?" — nothing of Jenkins' own pipeline structure.
CREATE TABLE pipelines (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id       BIGINT       NOT NULL REFERENCES projects (id),
    name             VARCHAR(200) NOT NULL,
    jenkins_job_path VARCHAR(500) NOT NULL, -- Jenkins full name, e.g. Team/UI/Web-Regression
    jenkins_base_url VARCHAR(500) NOT NULL, -- e.g. https://jenkins.company.com
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_pipelines_job_path ON pipelines (jenkins_job_path);

CREATE TABLE analyses (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_id        BIGINT       NOT NULL REFERENCES pipelines (id),
    -- Jenkins
    build_url          VARCHAR(1000) NOT NULL,
    job_name           VARCHAR(200)  NOT NULL,
    job_path           VARCHAR(500)  NOT NULL,
    build_number       INTEGER       NOT NULL,
    build_status       VARCHAR(30),
    -- Analysis (history list columns)
    analysis_status    VARCHAR(30)   NOT NULL,
    error_category     VARCHAR(30),
    exception_type     VARCHAR(500),
    headline           VARCHAR(500),
    -- AI / result
    error_reason       TEXT,
    result_json        TEXT          NOT NULL, -- AI answer, suggestions, test context, evidence (Jackson)
    relevant_logs      TEXT,
    last_200_lines     TEXT,
    -- LLM metrics
    model              VARCHAR(100),
    total_tokens       INTEGER,
    estimated_cost_usd NUMERIC(12, 6),
    -- Time
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    analyzed_at        TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_analyses_pipeline ON analyses (pipeline_id);
CREATE INDEX idx_analyses_analyzed_at ON analyses (analyzed_at DESC);
